r2dbc:
  datasources:
    source:
      url: r2dbc:pool:mysql://source-db:3306/db
      username: user
      password: password
      options: {}
    target:
      url: r2dbc:pool:mysql://target-db:3306/db
      username: user
      password: password
      options: {}
reconciliation:
  datasets:
    pets:
      source:
        datasourceRef: source
        query: >
          SELECT pet.id AS MigrationKey, category, name, status
          FROM pet
      target:
        datasourceRef: target
        query: >
          SELECT pet.id AS MigrationKey, category.name, pet.name, status
          FROM pet INNER JOIN category ON pet.category_id = category.id
    order-status:
      source:
        datasourceRef: source
        query: >
          SELECT
            order_status.id AS MigrationKey,
            pet_name,
            unix_timestamp(ordered_at),
            CASE
              WHEN status = 1 THEN 'placed'
              WHEN status = 2 THEN 'approved'
              WHEN status = 3 THEN 'delivered'
            END AS status_text,
            complete
          FROM order_status
      target:
        datasourceRef: target
        query: >
          SELECT
            order_status.id AS MigrationKey,
            pet.name,
            unix_timestamp(ordered_at),
            order_status.status,
            complete
          FROM order_status INNER JOIN pet ON order_status.pet_id = pet.id
    categories:
      source:
        datasourceRef: source
        query: >
          SELECT "# Categories" AS MigrationKey, count(distinct category) FROM pet
      target:
        datasourceRef: target
        query: >
          SELECT "# Categories" AS MigrationKey, count(*) FROM category
auth:
  username: admin
  password: admin
